language: ruby
rvm:
  - 1.9.3
  - 2.2.0
  - 2.1.0
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree
cache:
  bundler: true
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: ree
