language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.3.1
  - jruby-1.7.19
  - jruby-9.1.5.0
cache:
  bundler: true
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: ree
